n_channel: 96
sampling_rate: 30000
do_plot: true
use_hw: false
use_lsl: true
stream_name: "BioSemi"
sim_data_path: "data/save_data/test2.xdf"
use_layout: true
mapping_path: "config/layout_mea/Mapping_Utah.csv"
filter:
  class: "iir"
  order: 4
  lowcut: 100.0
  highcut: 8000.0
  type: "bandpass"  
recording:
  do_record: false
  duration: 10
  path: ""
  filename: ""
