n_channel: 10
sampling_rate: 3000
do_plot: true
use_hw: false
use_lsl: true
stream_name: "BioSemi"
sim_data_path: "data/sim_data/utah_dataset_snippet.mat"
save_recording: false
save_data_path: "/data/destination/path"
use_layout: true
mapping_path: "config/layout_mea/Mapping_Utah.csv"

filter:
  class: "iir"
  order: 2
  lowcut: 100.0
  highcut: 1150.0
  type: "bandpass"
