n_channel: 34
sampling_rate: 250
do_plot: true
use_hw: false
use_lsl: true
stream_name: "BioSemi"
sim_data_path: "data/sim_data/utah_dataset_snippet.mat"
save_recording: false
save_data_path: "/data/destination/path"
use_layout: true
mapping_path: "config/layout_mea/Mapping_Utah.csv"

filter:
  class: "fir"
  order: 21
  lowcut: .1
  highcut: 30.0
  type: "bandpass"
