n_channel: 36
sampling_rate: 1000
do_plot: true
use_hw: false
use_lsl: true
stream_name: "BioSemi"
sim_data_path: "data/sim_data/utah_dataset_snippet.mat"
use_layout: true
mapping_path: "config/layout_mea/Mapping_Utah.csv"
filter:
  class: "fir"
  order: 4
  lowcut: 0.1
  highcut: 100.0
  type: "bandpass"
recording:
  do_record: false
  duration: 10
  path: ""
  filename: ""
