n_channel: 100
sampling_rate: 30000
do_plot: true
use_hw: false
stream_name: "BioSemi"
sim_data_path: "../../data/sim_data/utah_dataset_snippet.mat" #"/media/k-dawg/Volume/PraxisProjektRohdaten/Simulator/C_Difficult1_noise005.mat" #"/media/k-dawg/Volume/PraxisProjektRohdaten/rps_20131016-115158-NSP1-001_MERGED.mat" # "/media/k-dawg/Volume/PraxisProjektRohdaten/Simulator/C_Difficult1_noise005.mat"
use_layout: false
mapping_path: "../../config/layout_mea/Mapping_Utah.csv"
filter:
  class: "iir"
  order: 4
  lowcut: 1500.0
  highcut: 3000.0
  type: "bandpass"
recording:
  do_record: false
  duration: 20
  path: ""
  filename: ""
buffer:
  size: 5
  window_size: 1000
model:
  path: "../model.pt"
  input_size: 32
