n_channel: 8
sampling_rate: 1000
do_plot: true
use_hw: true
use_lsl: true
stream_name: "Explore_8573_ExG"
sim_data_path: ""
use_layout: true
mapping_path: "config/layout_mea/Mapping_Utah.csv"
filter:
  class: "iir"
  order: 4
  lowcut: 0.1
  highcut: 300.0
  type: "bandpass"
recording:
  do_record: false
  duration: 10
  path: ""
  filename: ""
