n_channel: 25
sampling_rate: 3000
do_plot: false
use_hw: false
use_lsl: true
stream_name: "BioSemi"
sim_data_path: "/path/to/data"
save_recording: false
save_data_path: "/data/destination/path"

filter:
  class: "fir"
  order: 21
  lowcut: 100.0
  highcut: 1150.0
  type: "bandpass"
