n_channel: 96
sampling_rate: 30000
do_plot: false
use_hw: false
stream_name: "BioSemi"
sim_data_path: "/media/k-dawg/Volume/PraxisProjektRohdaten/rps_20131016-115158-NSP1-001_MERGED.mat"
use_layout: true
mapping_path: "config/layout_mea/Mapping_Utah.csv"
filter:
  class: "iir"
  order: 4
  lowcut: 10.0
  highcut: 9000.0
  type: "bandpass"
recording:
  do_record: true
  duration: 20
  path: "data/save_data"
  filename: "test4.xdf"
buffer:
  size: 5
  window_size: 1000
model:
  path: "processing/model.pt"
  input_size: 32
